prompt:
  name: Intelligent Prompt
  description: Sends a prompt to the default Home Assistant conversation agent, but injects entity intelligence first.
  fields:
    text:
      name: Text
      description: The command or question in natural language.
      required: true
      example: "Turn off the important lights and lock the doors."
      selector:
        text:

analyze_entities:
  name: Analyze Entities
  description: Manually triggers the analysis of all entities to update their importance scores.